###
GET http://localhost:8000 HTTP/1.1

###
POST http://localhost:8000/signUp HTTP/1.1
Content-Type: application/json

{
    "customerName": "Sailesh Patra2",
    "phone": 986565665,
    "email" : "sailesh2@gmail.com",
    "address": "Cuttack, Odisha",
    "aadharNo": "4553-92009-4621",
    "password": "Sailesh@123"
}

# {
#     "customerName": "Sailesh Patra",
#     "phone": 986565665,
#     "email" : "sailes@gmail.com",
#     "address": "Cuttack, Odisha",
#     "aadharNo": "4553-9009-4621",
#     "password": "Sailesh@123"
# }


###
POST http://localhost:8000/signIn HTTP/1.1
Content-Type: application/json

{
    "email":"sailesh@gmail.com",
    "password": "Sailesh@123"
}
